
name: build

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      
      - uses: actions/checkout@v3
      
      - name: Load configuration from repo
        run: |
          cat config
          cat config >> $GITHUB_ENV
       
      - name: build openwrt image
        uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          profile: armvirt-32
          openwrt-version: ${{ env.openwrt_version }}
          packages: ${{ env.packages }}
          files: files
          #disabled-services: dhcp
         # extra-image-name: useless
          
      - uses: izer-xyz/imagine/.github/workflows/test.yml@main
